version: '3.8'

services:
  backend-prod:
    image: delfisalinasmich/weblearn-backend:v1.0
    container_name: weblearn-backend-prod
    ports:
      - "8082:8080"
    env_file:
      - .env.prod
    depends_on:
      - db-prod
    networks:
      - prod-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  frontend-prod:
    image: delfisalinasmich/weblearn-frontend:v1.0
    container_name: weblearn-frontend-prod
    ports:
      - "8002:80"
    env_file:
      - .env.prod
    depends_on:
      - backend-prod
    networks:
      - prod-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  db-prod:
    image: mysql:8.0
    container_name: weblearn-db-prod
    ports:
      - "3309:3306"
    env_file:
      - .env.prod
    volumes:
      - mysql_data_prod:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    networks:
      - prod-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

volumes:
  mysql_data_prod:

networks:
  prod-network:
    driver: bridge
